apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  namespace: wordpress-app
data:
  WORDPRESS_DB_HOST: database-service.wordpress-db.svc.cluster.local:3306
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress